### PR TITLE
Force radius to be positive; fixes #26

### LINKED ISSUE #26: Minor: You are able to set radius to be negative
There is an issue where you are able to set radius to be negative.
___
1) Start at main page ( http://ezpick.herokuapp.com/ )

2) Click "Create" button

3) Set a valid meeting name, close out time, 30 minute duration, name, email, and schedule any dates.  But set Radius to a negative number such as "-300" and you will be allowed to submit it with the "Submit Your Meeting" button with this radius when it shouldn't be valid.

4) Now send an email invite for this submission to a valid email address.

5) In the email address provider for that email, open up the link.

6) Put valid inputs into this form, then click "Submit Response" it seems to always say "Submission failed! Please try again", which may be a problem with the radius being negative.

In console, I get the message "Failed to load resource: the server responded with a status of 404 (Not Found)", originating from "/api/response/create".

Browser: Google Chrome

### PR DESCRIPTION
**Pull request by zmbc**

### CODE REVIEW

File: client/src/Components/Create/Create.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ class Create extends Component {
                 {/*radius field*/}
                 <div className="form-group">
                   <label>Radius</label>
-                  <input name="radius" className="form-control" type="number" placeholder="Type the radius in meters the meeting should be within" required />
+                  <input name="radius" className="form-control" type="number" min="1" placeholder="Type the radius in meters the meeting should be within" required />
```
Comment (juimin) [inline client/src/Components/Create/Create.js:87]: So this doesn't actually prevent the input from rejecting negative inputs, only limits it if you use the arrows.

Comment (juimin) [reply client/src/Components/Create/Create.js:87]: Not actually sure how to solve this, everything I have tried won't work lol.

**Review by juimin — DISMISSED** [review]

**Review by juimin — APPROVED** [review]
